### ISSUE TITLE
Sample Methods => Dict

### ISSUE THREAD

**Issue by norton120** [norton120/SnowShu#13]
## Why?

right now sample methods are consumed by the config parser as strings, and the needed props are attributes of the sources object. this is gross and wrong and very limiting. 

## Def of Done:

if sample methods were a dict with each of their required attributes passed as params, this would mean:

* params are nicely contained inside the sample method they refer to
* adding relation-level sample methods becomes trivial

## How:

here’s the general idea. Move from 

```
source:
  include_outliers:True
  sample_method: Bernoulli
  probability: 50
```

To:

```
source:
  include_outliers:True
  sample_method:
    bernoulli:
      probability: 50
```

‌

[Issue created by ethanknox: 2020-01-20]
[Last updated on bitbucket: 2020-01-27]

[Comment created by ethanknox: 2020-01-27]
no longer needed due to https://bitbucket.org/healthunion/snowshu/issues/21/sample-size-methodology-support
